name: Build Companion Module TGZ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .tgz package
        run: npm pack

      - name: Get package filename
        id: get_filename
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TGZ_FILE="${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz"
          echo "TGZ_FILE=${TGZ_FILE}" >> $GITHUB_ENV
          echo "Generated TGZ: $TGZ_FILE"

      - name: Upload .tgz as artifact
        # Dit is de aangepaste regel
        uses: actions/upload-artifact@v4 
        with:
          name: companion-module-tgz
          path: ${{ env.TGZ_FILE }}
